### ISSUE TITLE
Does this have to be on the pro version?

### ISSUE THREAD

**Issue by robrohan** [owainlewis/emacs-visual-studio-2013#1]
I tried installing this and it says "This extension is not installable on any currently installed products".  I only have VS Express 2013 for Web, and I noticed the XML has "Pro" in there, does that mean this wont work on the Express editions or can I change Pro to something else?

Not really an issue, more of a question I suppose.

**Comment by complexzeros** [comment]
If you look at the stackoverflow.com link in the README.md, there is an answer describing how to make it work for the express editions.

**Comment by owainlewis** [comment]
Thanks @complexzeros.
